### ISSUE TITLE
/cities/<city> doesn't work as expected with spaces inside city name

### ISSUE THREAD

**Issue by sozuki** [AliceEnjoyer/Weather_Predictor#5]
![image](https://github.com/AliceEnjoyer/Weather_Predictor/assets/146732028/917c28e0-d178-46df-b6ae-4f0336f7021e)
![image](https://github.com/AliceEnjoyer/Weather_Predictor/assets/146732028/62ef7668-50f4-4c62-94e3-0f6b573787e8)
Expected : /cities/new_york or /cities/new%20%york to work

**Comment by soloclimb** [comment]
fixed in commit: 50cb247 (main)
