### ISSUE TITLE
Add paginated fetching for cities

### ISSUE THREAD

**Issue by sozuki** [AliceEnjoyer/Weather_Predictor#6]
### **For infinite scrolling I need a paginated fetching.**

**What is paginated fetching?**
Paginated fetching is a technique used in web development to retrieve large sets of data from a server in smaller, manageable chunks or pages. This approach is commonly used when dealing with APIs that return a large number of items, such as lists of users, products, or posts.
The basic idea of paginated fetching is to break down the data into separate pages or segments, with each page containing a limited number of items. This allows clients (such as web browsers or mobile apps) to request and display data incrementally, reducing the load on both the server and the client.

**For example:**
imagine a list of cities 
`[
{name: 'city1'},
{name: 'city2'},
{name: 'city3'},
{name: 'city4'},
{name: 'city5'},
{name: 'city6'},
{name: 'city7'}
]`
api call where limit=2 page=1 would return `[{name: 'city1'},{name: 'city2'}]`
api call where limit=2 page=2 would return `[{name: 'city3'},{name: 'city4'}]`
api call where limit=2 page=3 would return `[{name: 'city5'},{name: 'city6'}]`
api call where limit=2 page=4 would return `[{name: 'city7'}]`
api call where limit=2 page=5 would return false or an error

**Comment by soloclimb** [comment]
Added in commit: 1e3c638
Examples (all cities): 
http://localhost:4000/cities?page=1&limit=10 - 10 records for 1st page
http://localhost:4000/cities?page=2&limit=10 - 10 records for 2st page (with offset of 10 records)
Examples (search cities): 
http://localhost:4000/cities/san?page=1&limit=10 - 10 records for 1st page
http://localhost:4000/cities/san?page=2&limit=10 - 10 records for 2st page (with offset of 10 records)
