### ISSUE TITLE
Add names to the values in the array of cities for readability

### ISSUE THREAD

**Issue by sozuki** [AliceEnjoyer/Weather_Predictor#7]
### Add names to the values in the array of cities for readability

![image](https://github.com/AliceEnjoyer/Weather_Predictor/assets/146732028/bf7c51e8-a795-44d1-b4fa-e7b594752ee5)
should be converted to
```
{
  name: 'Austin',
  country: 'USA',
  ...,
  uts: "-6"
}
```

**Comment by soloclimb** [comment]
Added in commit: 20f180e

**Comment by soloclimb** [comment]
added same functionality for get_all_cities() in commit: b328332
