### ISSUE TITLE
Total count of pages in /cities

### ISSUE THREAD

**Issue by sozuki** [AliceEnjoyer/Weather_Predictor#9]
## Why?
The maximum amount of cities is needed to determine whether or not to load the skeletons for the cities beforehand. 
## How?
If it's possible, add a separate route that will return total number of cities.
## Examples
/cities/total/${city} ->  number of cities available after search
/cities/total/B -> 2
/cities/total/n -> 2
/cities/total/ -> 5412

**Comment by soloclimb** [comment]
Added in commit: 1103d18
